name: Deploy React App
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint App
        run: npm run lint
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build App
        run: npm run build
